version: "3.4"

volumes:
  yarn-cache:
    driver: local
  mongo-data:
    driver: local
  # redis-data:
  #   driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - yarn-cache:/usr/local/share/.cache/yarn/
      - $PWD:/opt/app
    env_file:
      - $PWD/.env
    ports:
      - "${EXTERNAL_PORT}:${PORT}"
    command: ["npm", "start"]
    depends_on:
      - mongodb
    #   - redis

  mongodb:
    image: mongo:3.6-xenial
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - $PWD/mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh

  # redis:
  #   image: redis:6-alpine
  #   command: ['--port', '${REDIS_PORT}', '--requirepass', '${REDIS_PASSWORD}']
  #   volumes:
  #     - redis-data:/data
